name: onnxruntime_dart
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/captaindario/onnxruntime_dart

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.onnxruntime_dart
        pluginClass: OnnxruntimeDartPlugin
      ios:
        pluginClass: OnnxruntimeDartPlugin
      linux:
        pluginClass: OnnxruntimeDartPlugin
      macos:
        pluginClass: OnnxruntimeDartPlugin
      windows:
        pluginClass: OnnxruntimeDartPluginCApi
      web:
        pluginClass: OnnxruntimeDartWeb
        fileName: onnxruntime_dart_web.dart

