name: onnxruntime_dart
description: "Onnxruntime bindings for dart, run your favorite models on any platform!"
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.mecab_dart
        pluginClass: OnnxruntimeDartPlugin
      ios:
        pluginClass: OnnxruntimeDartPlugin
      windows:
        pluginClass: OnnxruntimeDartPluginCApi
      linux:
        pluginClass: OnnxruntimeDartPlugin
      macos:
        pluginClass: OnnxruntimeDartPlugin
      web: